version: '3.8'
services:
  movies:
    image: pdamodar6373/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: pdamodar6373/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: pdamodar6373/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: pdamodar6373/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
